# Generated by Django 5.1.4 on 2025-03-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterresult',
            name='user',
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='SemesterResult',
        ),
    ]
